[browsers]
personal = "Zen"
work = "Firefox"

[urls]
personal = [ "reddit.com", "news.ycombinator.com" ]
work = [ "atlassian.net", "meet.google.com", "figma.com", "mail.google.com" ]

[work_days]
end = "Fri"
start = "Mon"

[work_time]
end = "18:00"
start = "9:30"